services:
  algaposts-rabbitmq:
    container_name: algaposts-rabbitmq
    image: rabbitmq:3-management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - algaposts-rabbitmq:/var/lib/rabbitmq/
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
volumes:
  algaposts-rabbitmq: